language: android
dist: xenial
jdk:
  - openjdk8
android:
  components:
    - build-tools-29.0.3
    - android-29

install:
  - set -e
  - echo y | sdkmanager "ndk-bundle"
before_script:
  - export NDK=$ANDROID_HOME/ndk-bundle
script:
  # Build apk
  - "./gradlew assembleAfatRelease"
  # Build bundle apk
  - "./gradlew bundleAfatRelease"

after_success:
  - export name=$(find -name '*.apk')
  - curl https://api.telegram.org/bot${BOT_TOKEN}/sendDocument -X POST -F chat_id="$CHANNEL_ID" -F document="@$name" -F caption="$(git log -1)"
  - curl https://api.telegram.org/bot${BOT_TOKEN}/sendDocument -X POST -F chat_id="$CHANNEL_ID" -F document="@./TMessagesProj/build/outputs/bundle/afatRelease/TMessagesProj-afat-release.aab" -F caption="Bundle file"
