language: android
dist: trusty
jdk:
  - openjdk8
android:
  components:
    - build-tools-28.0.3
    - android-28

install:
  - set -e
  - echo y | sdkmanager "ndk-bundle"
before_script:
  - export NDK=$ANDROID_HOME/ndk-bundle
  - wget $FIREBASE_URL -O TMessagesProj/google-services.json
script:
  # Build
  - "./gradlew assembleAfatRelease"

after_success:
  - 'find | grep .apk'
